version: '3.9'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: automedml_backend
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: automedml_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
