translations = {
    "welcome_message": {
        "en": """This chat is dedicated to patient {name} {surname}.

Here you can discuss case-specific details and use AI-powered tools 
to assist in analyzing this patient’s medical data, such as diagnostic images, 
clinical history, or lab results.

⚠️ Important notice: The outputs generated by this system are for informational 
and educational purposes only. They do not constitute medical advice, and should not 
be used as a substitute for your own professional judgment. You remain solely 
responsible for all diagnoses, treatment decisions, and patient care.""",

        "pl": """Ten czat jest przeznaczony dla pacjenta {name} {surname}.

Tutaj możesz omawiać szczegóły dotyczące przypadku i korzystać z narzędzi 
opartych na sztucznej inteligencji do analizy danych medycznych pacjenta, 
takich jak obrazy diagnostyczne, historia kliniczna czy wyniki badań.

⚠️ Ważne: Wyniki generowane przez ten system mają charakter informacyjny 
i edukacyjny. Nie stanowią porady medycznej i nie mogą zastępować 
profesjonalnego osądu lekarza. Odpowiadasz w pełni za wszystkie decyzje 
dotyczące diagnozy, leczenia i opieki nad pacjentem."""
    },
    "research_result": {
        "en": "Research Result ({model}):\nDiagnosis: {label}\nConfidence: {prob:.2f}%",
        "pl": "Wynik badania ({model}):\nDiagnoza: {label}\nPewność: {prob:.2f}%"
    }
}
